version: "3.7"

services:
  api:
    build: ".docker/api"
    container_name: go-sample-api
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    working_dir: /src/app
    tty: true
    env_file:
      - app/.env
#    command: bash -c "cd app && realize start --server"
    command: sh ./scripts/api.sh
    depends_on:
      - mysql

#  nginx:
#    build: ".docker/nginx"
#    container_name: go-sample-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - api

  mysql:
    container_name: go-sample-mysql
    build: ".docker/mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./app/storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo

  minio:
    image: minio/minio
    container_name: go-sample-minio
    ports:
      - "9001:9001"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9001 --console-address :9002"

  redis:
    image: redis:6.2-buster
    container_name: go-sample-redis
    ports:
      - "6379:6379"

  openapi:
    container_name: go-sample-openapi
    image: swaggerapi/swagger-ui:latest
    tty: true
    volumes:
      - "./app/openapi/:/var/openapi"
    environment:
      SWAGGER_JSON: /var/openapi/openapi.json
    ports:
      - "8080:8080"

  create-bucket:
    container_name: go-sample-create-bucket
    image: minio/mc
    entrypoint: [ "" ]
    command:
      - /bin/sh
      - -c
      - |
        until (mc config host add minio http://minio:9001 access_key secret_key) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/public
        mc policy set public minio/public
        mc mb minio/private
        mc policy set private minio/private
        mc policy set private minio/private
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
    depends_on:
      - minio