FROM golang:1.18-buster

ENV CGO_ENABLED=0
ENV GO111MODULE=auto

RUN apt-get update
#    go get github.com/cespare/reflex && \
#    go get github.com/swaggo/swag/cmd/swag && \
#    go get github.com/golang/mock/mockgen@latest
#    go get github.com/gin-gonic/gin && \
#    go get -u github.com/jinzhu/gorm
